Here is what I have when I run the main class:

Connected to pydev debugger (build 243.23654.177)
--------------------------------------------------------------------------
Task 1. The function is called and started running.
book: Data Science
year: 2025
hw: Number 1
Task 1 finished

--------------------------------------------------------------------------
Task 2. The function is called and started running.
{'a': 12.25, 'b': 'ecneicS ataD', 'c': 0, 'd': [12, 11, 10], 'e': {13: 'x', 23: 'y'}}
Task 2 completed!

--------------------------------------------------------------------------
Task 3. The function is called and started running.
func1 call executed in 0.0473 sec
func2 call executed in 0.0157 sec
func1 call executed in 0.0318 sec
func2 call executed in 0.0000 sec
func1 call executed in 0.0634 sec
Task 3 completed!

--------------------------------------------------------------------------
All tasks completed!

Process finished with exit code 0